[2025-03-17T01:33:43.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:33:43.489+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:33:39.661059+00:00 [queued]>
[2025-03-17T01:33:43.500+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:33:39.661059+00:00 [queued]>
[2025-03-17T01:33:43.502+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:33:43.520+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2025-03-17 01:33:39.661059+00:00
[2025-03-17T01:33:43.527+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'ingest_data_task', 'manual__2025-03-17T01:33:39.661059+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpasv_m1p1']
[2025-03-17T01:33:43.530+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask ingest_data_task
[2025-03-17T01:33:43.531+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:33:43.532+0000] {standard_task_runner.py:72} INFO - Started process 305 to run task
[2025-03-17T01:33:43.595+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:33:39.661059+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:33:43.702+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T01:33:39.661059+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T01:33:39.661059+00:00'
[2025-03-17T01:33:43.703+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:33:43.854+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T01:33:47.465+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: PurchasesFINAL12312016csv.zip
[2025-03-17T01:33:47.730+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:33:48.218+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: BegInvFINAL12312016csv.zip
[2025-03-17T01:33:48.257+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:33:48.404+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: 2017PurchasePricesDeccsv.zip
[2025-03-17T01:33:48.429+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:33:48.570+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: VendorInvoices12312016csv.zip
[2025-03-17T01:33:48.615+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:33:49.081+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: EndInvFINAL12312016csv.zip
[2025-03-17T01:33:49.123+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:34:01.358+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: SalesFINAL12312016csv.zip
[2025-03-17T01:34:01.458+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:34:01.459+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:34:01.490+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:34:01.492+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=ingest_data_task, run_id=manual__2025-03-17T01:33:39.661059+00:00, execution_date=20250317T013339, start_date=20250317T013343, end_date=20250317T013401
[2025-03-17T01:34:01.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:34:01.693+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:34:01.701+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
