[2025-03-17T01:11:46.406+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:11:46.436+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:11:46.448+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:11:46.449+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:11:46.466+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2025-03-16 00:00:00+00:00
[2025-03-17T01:11:46.475+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'ingest_data_task', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmplr_v_ntf']
[2025-03-17T01:11:46.478+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:11:46.479+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask ingest_data_task
[2025-03-17T01:11:46.479+0000] {standard_task_runner.py:72} INFO - Started process 221 to run task
[2025-03-17T01:11:46.553+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:11:46.667+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T01:11:46.668+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:11:54.680+0000] {logging_mixin.py:190} INFO - Archivo descargado: /tmp/PurchasesFINAL12312016csv.zip
[2025-03-17T01:11:55.062+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: [Errno 2] No such file or directory: '/tmp/PurchasesFINAL12312016csv.zip'
[2025-03-17T01:11:55.064+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_dag.py", line 88, in ingest_data
    os.remove(local_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/PurchasesFINAL12312016csv.zip'
[2025-03-17T01:11:55.097+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_ingestion_minio_dag, task_id=ingest_data_task, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T011146, end_date=20250317T011155
[2025-03-17T01:11:55.176+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:11:55.177+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task ingest_data_task ([Errno 2] No such file or directory: '/tmp/PurchasesFINAL12312016csv.zip'; 221)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingestion_dag.py", line 88, in ingest_data
    os.remove(local_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/PurchasesFINAL12312016csv.zip'
[2025-03-17T01:11:55.206+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-17T01:11:55.243+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:11:55.246+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-17T01:31:22.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:31:22.104+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:31:22.116+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:31:22.117+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:31:22.139+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2025-03-16 00:00:00+00:00
[2025-03-17T01:31:22.158+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:31:22.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'ingest_data_task', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp7xq286gw']
[2025-03-17T01:31:22.160+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2025-03-17T01:31:22.161+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask ingest_data_task
[2025-03-17T01:31:22.242+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:31:22.361+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T01:31:22.363+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:31:22.580+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T01:31:26.398+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: PurchasesFINAL12312016csv.zip
[2025-03-17T01:31:26.475+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:31:26.877+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: BegInvFINAL12312016csv.zip
[2025-03-17T01:31:27.485+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:31:27.661+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: 2017PurchasePricesDeccsv.zip
[2025-03-17T01:31:27.682+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:31:27.798+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: VendorInvoices12312016csv.zip
[2025-03-17T01:31:27.818+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:31:28.288+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: EndInvFINAL12312016csv.zip
[2025-03-17T01:31:28.342+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:31:40.742+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: SalesFINAL12312016csv.zip
[2025-03-17T01:31:40.844+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:31:40.845+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:31:40.866+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:31:40.867+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=ingest_data_task, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T013122, end_date=20250317T013140
[2025-03-17T01:31:40.972+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:31:40.999+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:31:41.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-17T02:07:25.756+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T02:07:25.794+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T02:07:25.818+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T02:07:25.819+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T02:07:25.839+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2025-03-16 00:00:00+00:00
[2025-03-17T02:07:25.851+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'ingest_data_task', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpn19j9mda']
[2025-03-17T02:07:25.854+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask ingest_data_task
[2025-03-17T02:07:25.855+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T02:07:25.857+0000] {standard_task_runner.py:72} INFO - Started process 308 to run task
[2025-03-17T02:07:25.933+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.ingest_data_task scheduled__2025-03-16T00:00:00+00:00 [running]> on host d6608b866a00
[2025-03-17T02:07:26.057+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T02:07:26.058+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T02:07:26.287+0000] {logging_mixin.py:190} INFO - El bucket rawdata-20250317 ya existe.
[2025-03-17T02:07:32.354+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: PurchasesFINAL12312016csv.zip
[2025-03-17T02:07:34.654+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: PurchasesFINAL12312016csv.zip
[2025-03-17T02:07:35.096+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: BegInvFINAL12312016csv.zip
[2025-03-17T02:07:37.124+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: BegInvFINAL12312016csv.zip
[2025-03-17T02:07:37.277+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: 2017PurchasePricesDeccsv.zip
[2025-03-17T02:07:37.874+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: 2017PurchasePricesDeccsv.zip
[2025-03-17T02:07:38.027+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: VendorInvoices12312016csv.zip
[2025-03-17T02:07:38.065+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: VendorInvoices12312016csv.zip
[2025-03-17T02:07:38.517+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: EndInvFINAL12312016csv.zip
[2025-03-17T02:07:38.873+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: EndInvFINAL12312016csv.zip
[2025-03-17T02:08:00.436+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: SalesFINAL12312016csv.zip
[2025-03-17T02:08:17.388+0000] {logging_mixin.py:190} INFO - Archivo subido a MinIO: SalesFINAL12312016csv.zip
[2025-03-17T02:08:17.397+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T02:08:17.417+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T02:08:17.418+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=ingest_data_task, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T020725, end_date=20250317T020817
[2025-03-17T02:08:18.012+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T02:08:18.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
