[2025-03-17T01:31:20.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:31:20.609+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:31:20.623+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T01:31:20.624+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:31:20.642+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_bucket_task> on 2025-03-16 00:00:00+00:00
[2025-03-17T01:31:20.651+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'create_bucket_task', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmp5xk0uies']
[2025-03-17T01:31:20.656+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask create_bucket_task
[2025-03-17T01:31:20.657+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=250) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:31:20.658+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-03-17T01:31:20.756+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:31:20.869+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='create_bucket_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T01:31:20.870+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:31:21.098+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T01:31:21.100+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:31:21.130+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:31:21.131+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=create_bucket_task, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T013120, end_date=20250317T013121
[2025-03-17T01:31:21.236+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:31:21.287+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:31:21.290+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-17T02:07:24.077+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T02:07:24.111+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T02:07:24.124+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T02:07:24.125+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T02:07:24.141+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_bucket_task> on 2025-03-16 00:00:00+00:00
[2025-03-17T02:07:24.151+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'create_bucket_task', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpn2_dqo6e']
[2025-03-17T02:07:24.155+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_bucket_task
[2025-03-17T02:07:24.159+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=299) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T02:07:24.160+0000] {standard_task_runner.py:72} INFO - Started process 302 to run task
[2025-03-17T02:07:24.230+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.create_bucket_task scheduled__2025-03-16T00:00:00+00:00 [running]> on host d6608b866a00
[2025-03-17T02:07:24.360+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='create_bucket_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T02:07:24.361+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T02:07:24.557+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T02:07:24.558+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T02:07:24.577+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T02:07:24.578+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=create_bucket_task, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T020724, end_date=20250317T020724
[2025-03-17T02:07:24.657+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T02:07:24.718+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T02:07:24.721+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
