[2025-03-17T01:37:13.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:37:13.566+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:37:10.986488+00:00 [queued]>
[2025-03-17T01:37:13.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:37:10.986488+00:00 [queued]>
[2025-03-17T01:37:13.580+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:37:13.599+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_bucket_task> on 2025-03-17 01:37:10.986488+00:00
[2025-03-17T01:37:13.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'create_bucket_task', 'manual__2025-03-17T01:37:10.986488+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpotzuzkpl']
[2025-03-17T01:37:13.610+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask create_bucket_task
[2025-03-17T01:37:13.611+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:37:13.613+0000] {standard_task_runner.py:72} INFO - Started process 378 to run task
[2025-03-17T01:37:13.679+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.create_bucket_task manual__2025-03-17T01:37:10.986488+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:37:13.788+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='create_bucket_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T01:37:10.986488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T01:37:10.986488+00:00'
[2025-03-17T01:37:13.789+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:37:13.938+0000] {logging_mixin.py:190} INFO - Error al crear el bucket: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.
[2025-03-17T01:37:13.939+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:37:13.953+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:37:13.954+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=create_bucket_task, run_id=manual__2025-03-17T01:37:10.986488+00:00, execution_date=20250317T013710, start_date=20250317T013713, end_date=20250317T013713
[2025-03-17T01:37:14.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:37:14.060+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:37:14.064+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
