[2025-03-17T01:23:41.942+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T01:23:41.972+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:23:39.058374+00:00 [queued]>
[2025-03-17T01:23:41.984+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:23:39.058374+00:00 [queued]>
[2025-03-17T01:23:41.985+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T01:23:42.002+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2025-03-17 01:23:39.058374+00:00
[2025-03-17T01:23:42.009+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_minio_dag', 'ingest_data_task', 'manual__2025-03-17T01:23:39.058374+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpryejm3gg']
[2025-03-17T01:23:42.012+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask ingest_data_task
[2025-03-17T01:23:42.015+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=230) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T01:23:42.016+0000] {standard_task_runner.py:72} INFO - Started process 231 to run task
[2025-03-17T01:23:42.086+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_minio_dag.ingest_data_task manual__2025-03-17T01:23:39.058374+00:00 [running]> on host 643acaa02cac
[2025-03-17T01:23:42.227+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_minio_dag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T01:23:39.058374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T01:23:39.058374+00:00'
[2025-03-17T01:23:42.228+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T01:23:45.732+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: PurchasesFINAL12312016csv.zip
[2025-03-17T01:23:45.914+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:23:46.327+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: BegInvFINAL12312016csv.zip
[2025-03-17T01:23:46.604+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:23:46.758+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: 2017PurchasePricesDeccsv.zip
[2025-03-17T01:23:46.787+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:23:46.907+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: VendorInvoices12312016csv.zip
[2025-03-17T01:23:46.929+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:23:47.383+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: EndInvFINAL12312016csv.zip
[2025-03-17T01:23:47.417+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the PutObject operation: The specified bucket is not valid.
[2025-03-17T01:23:58.162+0000] {logging_mixin.py:190} INFO - Archivo descargado en memoria: SalesFINAL12312016csv.zip
[2025-03-17T01:23:58.227+0000] {logging_mixin.py:190} INFO - Error al subir archivo a MinIO: An error occurred (InvalidBucketName) when calling the CreateMultipartUpload operation: The specified bucket is not valid.
[2025-03-17T01:23:58.227+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T01:23:58.244+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T01:23:58.245+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_minio_dag, task_id=ingest_data_task, run_id=manual__2025-03-17T01:23:39.058374+00:00, execution_date=20250317T012339, start_date=20250317T012341, end_date=20250317T012358
[2025-03-17T01:23:58.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T01:23:58.347+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T01:23:58.350+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
